#define CRYPTO_VERSION "1.2.5"

// AEAD defines
#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 16
#define CRYPTO_ABYTES 16
#define CRYPTO_NOOVERLAP 1
#define ASCON_AEAD_RATE 16

// Hash defines
#define CRYPTO_BYTES 32
#define ASCON_HASH_OUTLEN 32 /* HASH */
#define ASCON_HASH_ROUNDS 8
